apiVersion: v1
kind: Secret
metadata:
  name: groupsapp-secrets
type: Opaque
stringData:
  JWT_SECRET: "REPLACE_WITH_STRONG_JWT_SECRET"
  POSTGRES_PASSWORD: "REPLACE_WITH_RDS_PASSWORD"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
  AWS_ACCESS_KEY_ID: "REPLACE_IF_NOT_USING_IRSA"
  AWS_SECRET_ACCESS_KEY: "REPLACE_IF_NOT_USING_IRSA"
  AWS_SESSION_TOKEN: "REPLACE_IF_NOT_USING_IRSA"
